name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: report
        path: playwright-report/
        retention-days: 30
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      if: always()
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Upload to S3 bucket
      id: S3
      if: always()
      env:
         REPORT_DIR: playwright-report-${{ github.run_id }}
      run: |
         echo "REPORT_DIR=$REPORT_DIR" >> $GITHUB_ENV
         aws s3 cp playwright-report/. s3://${{ secrets.AWS_S3_BUCKET }}/$REPORT_DIR --recursive